// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {kube} from '../models';

export function ListContexts():Promise<kube.Kubeconfig>;

export function PingContext(arg1:string):Promise<kube.ServerVersion>;
