// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListConfigMaps(arg1, arg2) {
  return window['go']['app']['App']['ListConfigMaps'](arg1, arg2);
}

export function ListContexts() {
  return window['go']['app']['App']['ListContexts']();
}

export function ListDeployments(arg1, arg2) {
  return window['go']['app']['App']['ListDeployments'](arg1, arg2);
}

export function ListNamespaces(arg1) {
  return window['go']['app']['App']['ListNamespaces'](arg1);
}

export function ListPods(arg1, arg2) {
  return window['go']['app']['App']['ListPods'](arg1, arg2);
}

export function ListSecrets(arg1, arg2) {
  return window['go']['app']['App']['ListSecrets'](arg1, arg2);
}

export function ListServices(arg1, arg2) {
  return window['go']['app']['App']['ListServices'](arg1, arg2);
}

export function PingContext(arg1) {
  return window['go']['app']['App']['PingContext'](arg1);
}

export function StartWatch(arg1) {
  return window['go']['app']['App']['StartWatch'](arg1);
}

export function StopWatch(arg1) {
  return window['go']['app']['App']['StopWatch'](arg1);
}
