// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {kube} from '../models';

export function ListContexts():Promise<kube.Kubeconfig>;

export function ListNamespaces(arg1:string):Promise<Array<kube.NamespaceInfo>>;

export function ListPods(arg1:string,arg2:string):Promise<Array<kube.PodInfo>>;

export function PingContext(arg1:string):Promise<kube.ServerVersion>;

export function StartWatch(arg1:string):Promise<void>;

export function StopWatch(arg1:string):Promise<void>;
