// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListContexts() {
  return window['go']['app']['App']['ListContexts']();
}

export function PingContext(arg1) {
  return window['go']['app']['App']['PingContext'](arg1);
}
