// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyResourceYAML(arg1, arg2) {
  return window['go']['app']['App']['ApplyResourceYAML'](arg1, arg2);
}

export function DeleteResource(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['DeleteResource'](arg1, arg2, arg3, arg4);
}

export function GetConfigMap(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetConfigMap'](arg1, arg2, arg3);
}

export function GetCronJob(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetCronJob'](arg1, arg2, arg3);
}

export function GetDaemonSet(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetDaemonSet'](arg1, arg2, arg3);
}

export function GetDeployment(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetDeployment'](arg1, arg2, arg3);
}

export function GetIngress(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetIngress'](arg1, arg2, arg3);
}

export function GetJob(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetJob'](arg1, arg2, arg3);
}

export function GetNamespace(arg1, arg2) {
  return window['go']['app']['App']['GetNamespace'](arg1, arg2);
}

export function GetNode(arg1, arg2) {
  return window['go']['app']['App']['GetNode'](arg1, arg2);
}

export function GetPersistentVolume(arg1, arg2) {
  return window['go']['app']['App']['GetPersistentVolume'](arg1, arg2);
}

export function GetPersistentVolumeClaim(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetPersistentVolumeClaim'](arg1, arg2, arg3);
}

export function GetPod(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetPod'](arg1, arg2, arg3);
}

export function GetReplicaSet(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetReplicaSet'](arg1, arg2, arg3);
}

export function GetResourceYAML(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GetResourceYAML'](arg1, arg2, arg3, arg4);
}

export function GetSecret(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetSecret'](arg1, arg2, arg3);
}

export function GetService(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetService'](arg1, arg2, arg3);
}

export function GetStatefulSet(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetStatefulSet'](arg1, arg2, arg3);
}

export function GetStorageClass(arg1, arg2) {
  return window['go']['app']['App']['GetStorageClass'](arg1, arg2);
}

export function ListConfigMaps(arg1, arg2) {
  return window['go']['app']['App']['ListConfigMaps'](arg1, arg2);
}

export function ListContexts() {
  return window['go']['app']['App']['ListContexts']();
}

export function ListCronJobs(arg1, arg2) {
  return window['go']['app']['App']['ListCronJobs'](arg1, arg2);
}

export function ListDaemonSets(arg1, arg2) {
  return window['go']['app']['App']['ListDaemonSets'](arg1, arg2);
}

export function ListDeployments(arg1, arg2) {
  return window['go']['app']['App']['ListDeployments'](arg1, arg2);
}

export function ListEvents(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ListEvents'](arg1, arg2, arg3, arg4);
}

export function ListIngresses(arg1, arg2) {
  return window['go']['app']['App']['ListIngresses'](arg1, arg2);
}

export function ListJobs(arg1, arg2) {
  return window['go']['app']['App']['ListJobs'](arg1, arg2);
}

export function ListNamespaces(arg1) {
  return window['go']['app']['App']['ListNamespaces'](arg1);
}

export function ListNodes(arg1) {
  return window['go']['app']['App']['ListNodes'](arg1);
}

export function ListPersistentVolumeClaims(arg1, arg2) {
  return window['go']['app']['App']['ListPersistentVolumeClaims'](arg1, arg2);
}

export function ListPersistentVolumes(arg1) {
  return window['go']['app']['App']['ListPersistentVolumes'](arg1);
}

export function ListPodMetrics(arg1, arg2) {
  return window['go']['app']['App']['ListPodMetrics'](arg1, arg2);
}

export function ListPods(arg1, arg2) {
  return window['go']['app']['App']['ListPods'](arg1, arg2);
}

export function ListPortForwards() {
  return window['go']['app']['App']['ListPortForwards']();
}

export function ListReplicaSets(arg1, arg2) {
  return window['go']['app']['App']['ListReplicaSets'](arg1, arg2);
}

export function ListSecrets(arg1, arg2) {
  return window['go']['app']['App']['ListSecrets'](arg1, arg2);
}

export function ListServices(arg1, arg2) {
  return window['go']['app']['App']['ListServices'](arg1, arg2);
}

export function ListStatefulSets(arg1, arg2) {
  return window['go']['app']['App']['ListStatefulSets'](arg1, arg2);
}

export function ListStorageClasses(arg1) {
  return window['go']['app']['App']['ListStorageClasses'](arg1);
}

export function PingContext(arg1) {
  return window['go']['app']['App']['PingContext'](arg1);
}

export function PodLogTargets(arg1, arg2, arg3) {
  return window['go']['app']['App']['PodLogTargets'](arg1, arg2, arg3);
}

export function ResizeExec(arg1, arg2, arg3) {
  return window['go']['app']['App']['ResizeExec'](arg1, arg2, arg3);
}

export function SaveTextFile(arg1, arg2) {
  return window['go']['app']['App']['SaveTextFile'](arg1, arg2);
}

export function ScaleResource(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['ScaleResource'](arg1, arg2, arg3, arg4, arg5);
}

export function SendExecInput(arg1, arg2) {
  return window['go']['app']['App']['SendExecInput'](arg1, arg2);
}

export function StartExec(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['StartExec'](arg1, arg2, arg3, arg4, arg5);
}

export function StartPodLogs(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['StartPodLogs'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function StartPortForward(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['StartPortForward'](arg1, arg2, arg3, arg4, arg5);
}

export function StartWatch(arg1) {
  return window['go']['app']['App']['StartWatch'](arg1);
}

export function StopExec(arg1) {
  return window['go']['app']['App']['StopExec'](arg1);
}

export function StopPodLogs(arg1) {
  return window['go']['app']['App']['StopPodLogs'](arg1);
}

export function StopPortForward(arg1) {
  return window['go']['app']['App']['StopPortForward'](arg1);
}

export function StopWatch(arg1) {
  return window['go']['app']['App']['StopWatch'](arg1);
}
